# ── LOCAL OVERRIDE – never committed to git ──────────────────────────────────
# This file is listed in .gitignore. Copy it if you clone the repo and fill in
# your actual values before running locally.

spring.data.mongodb.uri=mongodb+srv://paulita1804_db_user:Jungkook18@empresariales1.y5v2h0j.mongodb.net/medipass
spring.data.mongodb.database=medipass

jwt.secret=bWVkaXBhc3NTZWNyZXRLZXkyMDI2TWVkaVBhc3NTZWNyZXRLZXkyMDI2TWVkaVBhc3NTZWNyZXRLZXkyMDI2TWVkaVBhc3NTZWNyZXQ=

spring.mail.username=558e1c4975f081
spring.mail.password=71897338baecf2
